### ISSUE TITLE
Support backend for Iroha `2.0.0-rc.1`

### ISSUE THREAD

**Issue by VladislavPopovSR** [soramitsu/iroha2-block-explorer-web#44]
Sibling of soramitsu/iroha2-block-explorer-backend#43

### TODO

Must:

- [x] Transactions & Instructions filters (#45)
- [x] Refer to blocks via their `height` everywhere (#45)
- [x] Shorten AccountId (#45)
- [x] Add transactions quantity (including rejected) on `BlocksList` , e.g. "3 (2 rejected)" (#45)
- [x] Add owned domains section on `AccountDetailsPage` (#45)
- [x] On `AssetList` fetch assets definitions instead (#45)
- [x] On `TransactionsList` print authority and the kind of instructions (let's rename it to "Kind of Executable" for clarity) - is it Instructions or WASM (#45)

Optional, but important:

- [ ] Integrate `vue-kakuyaku/core`. Also add refetching every n seconds;
- [ ] Add query params for pages that include table & filters;
- [ ] Divide `BaseTable` component and write unit tests;
- [x] Fix dropdown closing;
- [ ] Check i18n texts. Also error texts;
- [x] For all tables, display rows placeholders to avoid UI shifts on filters/page changes while new data is not loaded yet
- [x] For all tables, add "no data" filler.
- [ ] Tables: consider adding headers?
- [ ] #51
- [x] Research what data should show home page's disclaimer. Maybe fetch something?
- [x] Unified display of JSON values: monospace, formatted, colored, maybe even interactive
- [x] Proper "Age" display:
	- Adjust precision dynamically (e.g. not "1343 mins 35 secs ago", but "22 hours 23 minutes ago")
	- Add a timer to update rendered age according to precision (each N seconds, or minutes, or hours)
	- Add a tooltip to display an actual fixed timestamp instead of the age
- [ ] Add localisation for other languages
- [ ] Add total nodes display

### To be discussed 🕔

- `BaseContentBlock` closing arrow;
- Ipfs logos display;
- Unified search;
- Download list data. Maybe as csv or excel table;
- Display triggers, peers, data-model of executor, roles and permissions;
- Display blocks chart, total blocks amount and average block speed on BlocksList;
- Add explore section with socials, links to latest iroha articles and so on; 
- Add currency selection;

**Comment by VladislavPopovSR** [comment]
Created separated issues instead
